//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _123API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Accountinfo
    {
        public int ID { get; set; }
        public string Account_Name { get; set; }
        public string Male { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public Nullable<System.DateTime> Date_Created { get; set; }
        public string Created_By { get; set; }
    }
}
